import re
import os

# ============================================================
# USER SETTINGS
# ============================================================

INPUT_FILE = "merged_machine.gcode"
OUTPUT_FILE = "merged_rrf.gcode"

# Machine workspace limits
MAX_X = 100.0
MAX_Y = 100.0
MAX_Z = 100.0

# ============================================================
# RRF GLOBAL STARTUP
# ============================================================

RRF_HEADER = """
; ============================================================
; RRF 5AXIS START
; ============================================================

G21                         ; millimeters
G90                         ; absolute XYZBC
M83                         ; relative extrusion

; Pressure Advance
M572 D0 S0.04

; Fan off
M107

; ============================================================
; START PRINT
; ============================================================

"""

# ============================================================
# RRF GLOBAL END
# ============================================================

RRF_FOOTER = """

; ============================================================
; END PRINT
; ============================================================

M104 S0
M140 S0
M107
M84

"""

# ============================================================
# REMOVE RULES
# ============================================================

REMOVE_PREFIXES = [
    "M862",
    "M73",
    "M201",
    "M203",
    "M204",
    "M205",
    "M907",
    "M221",
    "M115",
]

REMOVE_EXACT = [
    "G80",
]

REMOVE_CONTAINS = [
    "generated by PrusaSlicer",
    "prusaslicer_config",
    "filament used",
    "estimated printing time",
]

# ============================================================
# HELPERS
# ============================================================

def should_remove(line):

    s = line.strip()

    for prefix in REMOVE_PREFIXES:
        if s.startswith(prefix):
            return True

    for exact in REMOVE_EXACT:
        if s.startswith(exact):
            return True

    for text in REMOVE_CONTAINS:
        if text in s:
            return True

    return False


def get_axis_value(s, axis):

    match = re.search(rf"{axis}(-?\d+\.?\d*)", s)

    if match:
        return float(match.group(1))

    return None


def exceeds_machine_limits(s):

    """
    Remove ONLY truly dangerous moves
    outside machine workspace.
    """

    if not s.startswith(("G0", "G1")):
        return False

    x = get_axis_value(s, "X")
    y = get_axis_value(s, "Y")
    z = get_axis_value(s, "Z")

    if x is not None and abs(x) > MAX_X:
        return True

    if y is not None and abs(y) > MAX_Y:
        return True

    if z is not None and abs(z) > MAX_Z:
        return True

    return False


# ============================================================
# LINE CONVERSION
# ============================================================

def convert_line(line):

    s = line.strip()

    # ========================================================
    # GENERIC REMOVALS
    # ========================================================

    if should_remove(line):
        return None

    # ========================================================
    # REMOVE HUGE OBJECT JSON
    # ========================================================

    if s.startswith("; objects_info"):
        return None

    # ========================================================
    # REMOVE WIPE SYSTEM
    # ========================================================

    if "_WIPE" in s:
        return None

    if ";WIPE_START" in s:
        return None

    if ";WIPE_END" in s:
        return None

    # ========================================================
    # REMOVE INTRO / PURGE
    # ========================================================

    if "intro line" in s:
        return None

    if "go outside print area" in s:
        return None

    if "Y-153" in s:
        return None

    # ========================================================
    # REMOVE OUT OF BOUNDS MOVES ONLY
    # ========================================================

    if exceeds_machine_limits(s):
        return None

    # ========================================================
    # REMOVE PARK / LIFT COMMENTS
    # ========================================================

    if "Move print head up" in s:
        return None

    if "Move print head further up" in s:
        return None

    if " park" in s:
        return None

    # ========================================================
    # REMOVE END-GCODE REMNANTS
    # ========================================================

    if "Filament-specific end gcode" in s:
        return None

    if s.startswith("G4"):
        return None

    if s == "M107 ; turn off fan":
        return None

    # ========================================================
    # REMOVE DUPLICATE SETUP
    # ========================================================

    if s == "G90 ; use absolute coordinates":
        return None

    if s == "M83 ; extruder relative mode":
        return None

    if s == "G21 ; set units to millimeters":
        return None

    if s == "M83 ; use relative distances for extrusion":
        return None

    # ========================================================
    # REMOVE EMPTY TYPE CUSTOM
    # ========================================================

    if s == ";TYPE:Custom":
        return None

    # ========================================================
    # REMOVE STARTUP COMMANDS
    # ========================================================

    if s.startswith((
        "M104",
        "M140",
        "M190",
        "M109",
        "G28",
        "G80"
    )):
        return None

    # ========================================================
    # REMOVE SHUTDOWN COMMANDS
    # ========================================================

    if s.startswith("M104 S0"):
        return None

    if s.startswith("M140 S0"):
        return None

    if s.startswith("M84"):
        return None

    # ========================================================
    # CONVERT M900 -> M572
    # ========================================================

    if s.startswith("M900"):

        match = re.search(r"K([0-9.]+)", s)

        if match:

            k = float(match.group(1))

            # Ignore absurd Prusa K20 compatibility line
            if k > 2:
                return None

            return f"M572 D0 S{k}\n"

        return None

    # ========================================================
    # REMOVE G28 W
    # ========================================================

    if s.startswith("G28 W"):
        return None

    return line


# ============================================================
# MAIN FUNCTION
# ============================================================

def convert_to_rrf(input_file, output_file):

    if not os.path.exists(input_file):
        print(f"❌ Missing input file: {input_file}")
        return None

    with open(input_file, "r", encoding="utf-8") as f:
        lines = f.readlines()

    processed = []

    inside_metadata = False

    for line in lines:

        s = line.strip()

        # ====================================================
        # KEEP PART MARKERS
        # ====================================================

        if "; ===== PART" in s:

            processed.append("\n" + s + "\n")
            continue

        # ====================================================
        # REMOVE PRUSA METADATA
        # ====================================================

        if "; prusaslicer_config = begin" in s:
            inside_metadata = True
            continue

        if "; prusaslicer_config = end" in s:
            inside_metadata = False
            continue

        if inside_metadata:
            continue

        # ====================================================
        # CONVERT LINE
        # ====================================================

        new_line = convert_line(line)

        if new_line is not None:
            processed.append(new_line)

    # ========================================================
    # CLEAN EMPTY LINES
    # ========================================================

    final_lines = []

    previous_blank = False

    for line in processed:

        blank = (line.strip() == "")

        if blank and previous_blank:
            continue

        final_lines.append(line)

        previous_blank = blank

    # ========================================================
    # WRITE OUTPUT
    # ========================================================

    with open(output_file, "w", encoding="utf-8") as f:

        f.write(RRF_HEADER)

        for line in final_lines:
            f.write(line)

        f.write(RRF_FOOTER)

    print(f"✅ Saved RRF file: {output_file}")

    return output_file


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":

    convert_to_rrf(INPUT_FILE, OUTPUT_FILE)
